#!/usr/bin/env bash
p="www.google.com"
co="15"
if [ "$#" -ge "1" ]; then
	arg="$(echo $1 | tr '[:upper:]' '[:lower:]')"
	if [ "$arg" == "-h" -o "$arg" == "--help" ]; then
		echo "Usage: nettest [ip or url] [number of times to ping]"
		echo "Default is equivalent to: ping -c $co $p"
		exit 0
	elif [ "$arg" != "web" ]; then
		p="$arg"
	fi
fi
if [ "$#" -ge "2" ]; then
	co="$2"
fi

ping -c "$co" "$p"